### ISSUE TITLE
Missing Input Type field of families config in CLI

### ISSUE THREAD

**Issue by paralta** [openclarity/vmclarity#479]
## Description

While testing the new Docker provider, I noticed that viper fails to unmarshal the Input Type string field when reading the families config yaml file. This causes the scan to fail due to the missing `InputType` field.

## Expected Behavior

When the configuration file contains the following
```
sbom:
  AnalyzersConfig: null
  AnalyzersList: null
  Enabled: true
  Inputs:
  - Input: /mnt/snapshot
    InputType: rootfs
  MergeWith: null 
```
the unmarshalled configuration in CLI should be `{true [syft trivy] [{/mnt/snapshot rootfs}] [] 0x4002002660}` (for example).

## Actual Behavior

For the same configuration, the unmarshalled configuration is currently `{{true [] [{/mnt/snapshot }] [] <nil>}`. Please notice the missing `rootfs` for input type.

## Affected Version

docker-provider

## Steps to Reproduce

1. Create a scan configuration with SBOM enabled and where an example `Input` is specified for SBOM
2. Start VMClarity and apply configuration
3. Check error message from SBOM scan

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue
