### ISSUE TITLE
Ddd a startTime and endTime to the AssetScan

### ISSUE THREAD

**Issue by sambetts-cisco** [openclarity/vmclarity#509]
I think we also need to add a startTime and endTime to the AssetScan itself. The start time should be set from the the moment the AssetScan moves from Pending to Scheduled and scanEndTime should be set when the AssetScan moves to Done or Failed. That will allow us to calculate the duration the AssetScan really took to scan from the point we start creating resources. We can also add cleanupEndTime, which is the point when the cleanup finishes which will give us the full e2e time for an AssetScan.

Adding these fields is something we need anyway in order to implement a per AssetScan timeout and I'm sure there are other use cases too.

_Originally posted by @sambetts-cisco in https://github.com/openclarity/vmclarity/pull/473#discussion_r1274864342_

**Comment by Horiodino** [comment]
Hii @sambetts-cisco i would like to work on this issue can  you provide the file where to add changes

**Comment by sambetts-cisco** [comment]
Hi @Horiodino! Thanks for wanting to pick this up! There are a few parts to this change:

* The API model is defined in `api/openapi.yaml`, in there you will find the AssetScan and AssetScanRelationship models. Both of those will need the new fields (startTime, endTime) adding to them.

* Once you modify api/openapi.yaml then you need to run `make gen-api` to generate the golang code from the API yaml.

* The new fields need to be added to the DB layer definition of AssetScan in `pkg/apiserver/database/gorm/odata.go`.

* The `pkg/orchestrator/assetscanwatcher` needs to be updated so that when the AssetScan transitions from Pending to Scheduled startTime is set.

* `pkg/cli/state/vmclarity.go` needs to be updated to PATCH endTime when it moves the AssetScan to "DONE" state.

**Comment by Horiodino** [comment]
@sambetts-cisco  thankyou for providing the info i will solve this issue as soon as possible 🙂🙂

**Comment by Horiodino** [comment]
@sambetts-cisco  is it correct ```
    AssetScans:
      type: object
      properties:

        count:
          type: integer
          description: Total asset scans count according to the given filters
          readOnly: true
        items:
          type: array
          description: List of asset scans according to the given filters and page.
            List length must be lower or equal to pageSize.
          items:
            $ref: '#/components/schemas/AssetScan'
          readOnly: true
        startTime:
          type: string
          format: date-time
          description: The start time of the asset scan.
        endTime:
          type: string
          format: date-time
          description: The end time of the asset scan.```                                                          

```
AssetScanRelationship:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: string
              # TODO(sambetts) Decide if we want the validation here by having
              # separate schemas for GET, POST and PATCH.
              #
              # We can't make anything readOnly or required here if we want to
              # use the same schema for PATCH otherwise it will require you
              # always send the required fields and remove the readOnly fields
              # on the client side.
              #
              # readOnly: true
            startTime:
              type: string
              format: date-time
            endTime:
              type: string
              format: date-time 
```

**Comment by Horiodino** [comment]
@sambetts-cisco  is it correct 
```  
    AssetScans:
      type: object
      properties:

        count:
          type: integer
          description: Total asset scans count according to the given filters
          readOnly: true
        items:
          type: array
          description: List of asset scans according to the given filters and page.
            List length must be lower or equal to pageSize.
          items:
            $ref: '#/components/schemas/AssetScan'
          readOnly: true
        startTime:
          type: string
          format: date-time
          description: The start time of the asset scan.
        endTime:
          type: string
          format: date-time
          description: The end time of the asset scan.
```

```
    AssetScanRelationship:
      type: object
      allOf:
        - type: object
          properties:
            id:
              type: string
              # TODO(sambetts) Decide if we want the validation here by having
              # separate schemas for GET, POST and PATCH.
              #
              # We can't make anything readOnly or required here if we want to
              # use the same schema for PATCH otherwise it will require you
              # always send the required fields and remove the readOnly fields
              # on the client side.
              #
              # readOnly: true
            startTime:
              type: string
              format: date-time
            endTime:
              type: string
              format: date-time
```
